import { test, expect } from '@playwright/test'

test('recipe preview, saving, and collection persistence', async ({ page }) => {
  await page.goto('/')
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await expect(page.getByRole('heading', { level: 1 })).toContainText('inspiration')
  await page.getByRole('button', { name: 'Save your first recipe' }).click()
  await page.getByLabel('Recipe URL').fill('https://example.com/pasta')
  await page.getByRole('button', { name: 'Preview a sample recipe' }).click()
  await expect(page.getByRole('dialog')).toContainText('Creamy tomato & basil pasta')
  await page.getByRole('button', { name: 'Save to my collection' }).click()
  await page.getByRole('button', { name: 'Close recipe' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'View your collection' }).click()
  await expect(page.locator('.recipe-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Unsave Creamy tomato & basil pasta' }).click()
  await expect(page.getByText('Your next favorite belongs here.')).toBeVisible()
})

test('mobile layout and navigation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Toggle navigation' }).click()
  await page.getByRole('link', { name: 'How it works' }).click()
  await expect(page.getByRole('button', { name: 'Toggle navigation' })).toHaveAttribute('aria-expanded', 'false')
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
})

test('import dialog preserves text and keyboard focus through the recipe preview', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'Save your first recipe' })
  await trigger.click()
  const close = page.getByRole('button', { name: 'Close import' })
  await expect(close).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Preview a sample recipe' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(close).toBeFocused()
  await page.getByRole('tab', { name: 'Text', exact: true }).click()
  await page.getByLabel('Recipe text').fill('Flour, milk, eggs. Mix and cook pancakes.')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(page.getByLabel('Recipe text')).toHaveValue('Flour, milk, eggs. Mix and cook pancakes.')
  await page.getByRole('button', { name: 'Preview a sample recipe' }).click()
  await expect(page.getByRole('dialog')).toContainText('Slow Sunday pancakes')
  await expect(page.getByRole('button', { name: 'Close recipe' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
})

test('photo import validates selection and cancelled previews stay closed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Save your first recipe' }).click()
  await page.getByRole('tab', { name: 'Photo', exact: true }).click()
  await page.getByRole('button', { name: 'Preview a sample recipe' }).click()
  await expect(page.getByRole('alert')).toContainText('Choose a recipe photo')
  await page.locator('input[type=file]').setInputFiles({ name: 'recipe.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') })
  await page.getByRole('button', { name: 'Preview a sample recipe' }).click()
  await page.getByRole('button', { name: 'Close import' }).click()
  await page.waitForTimeout(1300)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Save your first recipe' }).click()
  await page.getByRole('button', { name: 'Preview a sample recipe' }).click()
  await expect(page.getByRole('dialog')).toContainText('The sunshine nourish bowl')
})
