import { BASE, resolveUnit } from '../../shared/utils/recipeText.ts'
import type { Food, Quantity } from '../../shared/types/recipe.ts'
import { kindOf } from './quantity.ts'
import entries from './ingredients.json' with { type: 'json' }

// The ingredient table (#132): what an ingredient is, matched by name, and how
// heavy a millilitre of it is, from USDA FoodData Central. The table is data
// checked in beside this file and regenerated by scripts/ingredients.ts, so
// matching stays synchronous and needs no database.

export type FoodEntry = {
  key: string
  // Null for a food FDC doesn't have: it matches, and has no density.
  fdcId: number | null
  // FDC's own description of the food, and the portion the density comes from.
  fdc?: string | null
  form: 'solid' | 'liquid'
  // Which FDC portion to read the density from, when the first cup or spoon
  // is the wrong one; "-" for none.
  pick?: string
  portion?: string | null
  gramsPerMl?: number | null
  en: string[]
  de: string[]
}

/** A name as the table compares it: lower case, no accents, no parenthetical, words only. */
export const matchKey = (name: string) => name
  .normalize('NFD').replace(/\p{M}/gu, '')
  .toLowerCase()
  .replace(/\([^)]*\)/g, ' ')
  .replace(/['’]/g, '')
  .replace(/[^\p{L}\p{N}%]+/gu, ' ')
  .trim()

type Language = 'en' | 'de'
const index: Record<Language, Map<string, FoodEntry>> = { en: new Map(), de: new Map() }
for (const entry of entries as FoodEntry[]) {
  for (const lang of ['en', 'de'] as const) for (const name of entry[lang]) index[lang].set(matchKey(name), entry)
}

// Words that say how an ingredient is prepared or how big it is, not what it
// is, and only those: "dried", "ground", "canned" and "cooked" make a
// different food, so they stay and the name either matches as written or not
// at all.
const DESCRIPTORS = {
  en: new Set(['fresh', 'freshly', 'large', 'small', 'medium', 'extra', 'ripe', 'organic', 'chopped', 'diced',
    'minced', 'sliced', 'grated', 'shredded', 'crushed', 'softened', 'melted', 'cold', 'chilled', 'warm',
    'boneless', 'skinless', 'whole', 'raw', 'peeled', 'finely', 'roughly', 'coarsely', 'thinly', 'packed',
    'sifted', 'good', 'quality', 'room', 'temperature', 'frozen', 'about', 'heaping', 'level',
    // "bone-in", "skin-on", which reach here as two words each.
    'bone', 'skin', 'in', 'on']),
  de: /^(frisch|gross|groß|klein|mittelgross|mittelgroß|reif|weich|kalt|warm|zimmerwarm|geschalt|gehackt|gerieben|fein|grob|bio|gewurfelt|zerlassen|geschmolzen|ganz|tiefgekuhlt|tk)(e|er|es|en|em)?$/,
}
const isDescriptor = (word: string, lang: Language) =>
  lang === 'en' ? DESCRIPTORS.en.has(word) : DESCRIPTORS.de.test(word)

// English plurals the table doesn't list: "tomatoes", "cherries", "peaches".
// German ones are listed, since no rule covers Ei/Eier and Zwiebel/Zwiebeln alike.
function singulars(text: string): string[] {
  if (!text.endsWith('s')) return []
  const stem = text.slice(0, -1)
  return [stem, ...(text.endsWith('ies') ? [`${text.slice(0, -3)}y`] : []), ...(text.endsWith('es') ? [text.slice(0, -2)] : [])]
}

function find(text: string, lang: Language): FoodEntry | null {
  const found = index[lang].get(text)
  if (found || lang === 'de') return found ?? null
  for (const singular of singulars(text)) {
    const entry = index.en.get(singular)
    if (entry) return entry
  }
  return null
}

/**
 * The table's entry for an ingredient's name, or null. The recipe's language
 * is tried first and the other one after it, since an English name in a
 * German recipe is common ("Cheddar"). Each part between commas is tried in
 * turn, since the food is usually first ("butter, softened") but not always
 * ("bone-in, skin-on chicken thighs"). Leading words that only describe
 * ("2 large eggs", "frischer Ingwer") are dropped one at a time; anything else
 * unmatched stays unmatched.
 */
export function matchFood(name: string, sourceLang: string): FoodEntry | null {
  const first: Language = sourceLang.toLowerCase().startsWith('de') ? 'de' : 'en'
  for (const part of name.split(',')) {
    const words = matchKey(part).split(' ').filter(Boolean)
    for (let start = 0; start < words.length; start++) {
      const text = words.slice(start).join(' ')
      const entry = find(text, first) ?? find(text, first === 'en' ? 'de' : 'en')
      if (entry) return entry
      if (!isDescriptor(words[start]!, 'en') && !isDescriptor(words[start]!, 'de')) break
    }
  }
  return null
}

const tenth = (value: number) => Math.round(value * 10) / 10

/**
 * An amount in grams for a solid and millilitres for a liquid, crossing
 * between weight and volume by the food's density. Null where it can't be
 * done: a count, a unit with no size ("1 slice"), or a crossing with no
 * density to cross by.
 */
export function canonicalAmount(quantity: Quantity | null, food: FoodEntry, sourceLang: string): Quantity | null {
  if (!quantity?.unit) return null
  const kind = kindOf(quantity.unit)
  const factor = BASE[resolveUnit(quantity.unit, sourceLang)]
  if (!factor || (kind !== 'mass' && kind !== 'volume')) return null
  const density = food.gramsPerMl ?? null
  const to = food.form === 'solid' ? 'g' : 'ml'
  const convert = (value: number): number | null => {
    const base = value * factor
    if ((kind === 'mass') === (to === 'g')) return tenth(base)
    if (!density) return null
    return tenth(to === 'g' ? base * density : base / density)
  }
  const value = convert(quantity.value)
  if (value === null) return null
  return { value, maxValue: quantity.maxValue === null ? null : convert(quantity.maxValue), unit: to }
}

/** What a recipe stores about a matched food: its key, and its density for converting in the browser. */
export const foodOf = (entry: FoodEntry): Food => ({ key: entry.key, gramsPerMl: entry.gramsPerMl ?? null })
